# Generated by Django 2.2.7 on 2019-11-29 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20191129_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='injury',
            name='isbn',
        ),
    ]
