# Generated by Django 2.2.7 on 2019-11-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_injury_isbn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_Of_Injury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a type of injury (e.g. Break, Burn)', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='injury',
            name='type_of_injury',
            field=models.ManyToManyField(help_text='Select a type of injury for this incident', to='catalog.Type_Of_Injury'),
        ),
    ]
