# Generated by Django 2.2.7 on 2019-12-02 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20191201_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='injury',
            name='person',
        ),
    ]
