# Generated by Django 2.2.7 on 2019-12-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20191203_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='injury',
            name='type_of_injury',
        ),
        migrations.AddField(
            model_name='injury',
            name='injury_type',
            field=models.IntegerField(choices=[(1, 'Burn'), (2, 'Break'), (3, 'Bleed'), (4, 'Contusion'), (5, 'Other')], default=1),
        ),
    ]
