# Generated by Django 2.2.7 on 2019-12-09 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0013_auto_20191203_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injury',
            name='injury_type',
            field=models.IntegerField(choices=[(1, 'Not bleeding'), (2, 'Spontanous bleed'), (3, 'Tramatic bleed'), (4, 'Post-Op bleed'), (5, 'Other')], default=1),
        ),
        migrations.CreateModel(
            name='BleedInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ticket_initated_by', models.IntegerField(choices=[(1, 'Staff'), (2, 'Patient'), (3, 'Parent'), (4, 'Spouse'), (5, 'Other')], default=1)),
                ('summary', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('bleed_type', models.IntegerField(choices=[(1, 'Not bleeding'), (2, 'Spontanous bleed'), (3, 'Tramatic bleed'), (4, 'Post-Op bleed'), (5, 'Other')], default=1)),
                ('bleed_location', models.IntegerField(choices=[(1, 'Joint'), (2, 'Muscle'), (3, 'Head'), (4, 'Other')], default=1)),
                ('bleed_location_details', models.CharField(max_length=200)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
