# Generated by Django 2.2.7 on 2019-12-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20191208_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='bleedinfo',
            name='num_of_days_extra_factor_was_used',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bleedinfo',
            name='summary',
            field=models.TextField(help_text='Enter a brief description of the bleed', max_length=1000),
        ),
    ]
