# Generated by Django 2.2.7 on 2019-12-09 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20191208_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='bleedinfo',
            name='did_patient_use_factor_yn',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=1),
        ),
        migrations.AddField(
            model_name='bleedinfo',
            name='did_patient_use_home_factor_yn',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=1),
        ),
        migrations.AddField(
            model_name='bleedinfo',
            name='home_factor_supply_details',
            field=models.CharField(default='na', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bleedinfo',
            name='name_of_extra_factor_drug',
            field=models.CharField(default='na', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bleedinfo',
            name='why_patinet_did_not_use_facor',
            field=models.CharField(default='na', max_length=200),
            preserve_default=False,
        ),
    ]
